name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      dockerfile:
        required: false
        type: string
        default: ./Dockerfile
      context:
        required: false
        type: string
        default: .
      environment:
        required: true
        type: string # staging | production
    secrets:
      GITHUB_TOKEN:
        required: true
    outputs:
      image-tag:
        description: "Built image tag"
        value: ${{ jobs.build-and-push.outputs.image-tag }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.meta.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}
          tags: |
            type=raw,value=${{ github.sha }},enable=${{ inputs.environment == 'staging' }}
            type=ref,event=tag,enable=${{ inputs.environment == 'production' }}
            type=semver,pattern={{version}},enable=${{ inputs.environment == 'production' }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ inputs.environment == 'production' }}
            type=semver,pattern={{major}},enable=${{ inputs.environment == 'production' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
