name: Production Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    uses: ./.github/workflows/build-and-push.yaml
    with:
      image_name: my-app
      environment: production
    secrets:
      GHCR_PAT: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.2

      - name: Change directory to Production
        run: cd infra/production && pwd && ls

      - name: Terraform Init
        run: pwd && ls && terraform init -backend-config="bucket=${{secrets.BUCKET_NAME}}" -backend-config="dynamodb_table=${{secrets.DYNAMODB_TABLE}}"

      - name: Terraform Apply (Production)
        run: terraform apply -auto-approve -var="app_name=myapp" -var="app_image=myapp:${{ needs.build.outputs.image-tag }}"
